name: "Conan Build"
description: "Setup Conan"
author: "offa"
branding:
  icon: "check-circle"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: "Setup pipx"
      if: runner.os == 'Linux'
      run: |
          apt-get update
          apt-get install -y pipx
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      shell: bash
    - name: "Setup Conan"
      run: |
        pipx install conan
        conan config install "${GITHUB_ACTION_PATH}/settings_user.yml"
        conan profile detect
      shell: bash
