name: ci

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc:16
          - gcc:15
          - clang:22
          - clang:21
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Conan Action
        uses: ./
      - name: Build
        run: test/ci_build.sh

  build_msvc:
    runs-on: windows-latest
    name: "msvc"
    steps:
      - uses: actions/checkout@main
      - name: Conan Action
        uses: ./
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756
      - name: Build
        run: test/ci_build.sh
        shell: bash

  build_osx:
    runs-on: macOS-latest
    name: "mac os"
    steps:
      - uses: actions/checkout@main
      - name: Conan Action
        uses: ./
      - name: Build
        run: test/ci_build.sh


  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: yamllint
        run: |
          pip install -U yamllint
          yamllint --strict settings_user.yml
